class ProjectModel {
  String projectTitle;
  String projectDescription;
  String? projectImageUrl = "";
  String? projectLink = "";
  String? githubLink = "";

  /// Display position — lower shows first. Ties keep data.json order.
  final int order;

  ProjectModel({
    required this.projectTitle,
    required this.projectDescription,
    this.projectImageUrl,
    this.projectLink,
    this.githubLink,
    this.order = 9999,
  });

  factory ProjectModel.fromJson(Map<String, dynamic> json) {
    return ProjectModel(
      projectTitle: json['title'] as String? ?? '',
      projectDescription: json['description'] as String? ?? '',
      projectImageUrl: json['imageUrl'] as String? ?? '',
      projectLink: json['liveUrl'] as String? ?? '',
      githubLink: json['githubUrl'] as String? ?? '',
      order: (json['order'] as num?)?.toInt() ?? 9999,
    );
  }

  ProjectPreviewType get previewType {
    if (projectLink != null && projectLink!.isNotEmpty) {
      return ProjectPreviewType.live;
    }

    if (githubLink != null && githubLink!.isNotEmpty) {
      return ProjectPreviewType.github;
    }

    return ProjectPreviewType.image;
  }
}

enum ProjectPreviewType { image, live, github }

final sampleProjects = [
  ProjectModel(
    projectTitle: 'Civic',
    projectDescription:
        'Civic is a mobile-first application designed to facilitate structured civic participation. It provides a unified platform where users can document local problems, engage with community-driven discussions, and connect with others based on shared interests and skills.',
    projectImageUrl: '',
    projectLink: '',
    githubLink: 'https://github.com/aravindpunyamantula/CIVIC',
  ),
  ProjectModel(
    projectTitle: "Cherries Cafe",
    projectDescription:
        "A high-performance, SEO-optimized landing page and web platform built to elevate the digital presence of Cherries Cafe, a premium vegetarian restaurant. The application serves as a dynamic digital storefront, driving customer acquisition through modern web design, integrated event booking tools, and automated customer retention features.",
    projectLink: "https://cherriescafe.in",
  ),
  ProjectModel(
    projectTitle: "Glamup Gifts",
    projectDescription:
        "A highly secure, SEO-optimized e-commerce landing page and digital storefront engineered for a premium gift shop. The platform balances discoverability with robust infrastructure, leveraging modern caching architectures and edge security protocols to deliver rapid load times and mitigate automated threat vectors.",
    projectLink: "https://glamupgifts.com",
  ),
  ProjectModel(
    projectTitle: "Offline-Support-ChatBot",
    projectDescription:
        """This project demonstrates how to build an offline AI-powered customer support chatbot using Ollama and the Llama 3.2 (3B) language model. The chatbot answers common e-commerce support queries such as order tracking, returns, payments, and account management. Unlike cloud-based AI services, this system runs entirely locally, ensuring that no customer data leaves the machine. This approach improves privacy, security, and cost efficiency by eliminating external API usage. The project also evaluates two prompt engineering techniques: Zero-Shot Prompting One-Shot Prompting The responses generated by the model are logged and manually evaluated based on relevance, coherence, and helpfulness. """,
    githubLink:
        "https://github.com/aravindpunyamantula/offline-support-chatbot",
  ),
  ProjectModel(
    projectTitle: 'LLM-Prompt-Router',
    projectDescription:
        "This project implements a Node.js service that routes user requests to specialized AI personas based on detected intent. Instead of using a single monolithic prompt for every request, the system first classifies the user's intent using an LLM, and then routes the request to an expert persona designed for that specific task.",
    githubLink: 'https://github.com/aravindpunyamantula/LLM-Prompt-Router',
  ),
  ProjectModel(
    projectTitle: 'Github Clone',
    projectDescription:
        'A Flutter-based GitHub clone app that allows users to explore GitHub repositories, view files, and navigate folders, using the GitHub API.',
    githubLink: 'https://github.com/aravindpunyamantula/Github_Clone',
  ),
];
